language: ruby
cache: bundler
sudo: false

rvm:
  - 2.6
  - 2.4

notifications:
    email: false

before_install: gem update --system
install: scripts/bootstrap
script: scripts/cibuild

env:
  matrix:
    - JEKYLL_VERSION="~> 3.5"
    - JEKYLL_VERSION="~> 3.8.0"
    - JEKYLL_VERSION=">= 4.0.0.pre.alpha1"