title: Arepa's Game Blog # The title of the blog
author: ArepaZombie # Your name 
email: jorgetorresmora99@gmail.com # your email shown in the footer
url: https://github.com/ArepaZombie/arepas-blog # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  A little blog were I put updates of my proyect: a videogame.
favicon: "./favicon.ico" # set the favicon of the site 
markdown: kramdown

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://avatars.githubusercontent.com/u/106775933?s=400&u=89eb344c1d5ffd95b49f686c2689b0bae33b0f15&v=4" # avatar in about page
  about_you: I'm just starting to learn to code and program. And I love this. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: ArepaZombie
    github:  ArepaZombie
    #rss: RSS
    # dribbble: 
    #facebook: huangyz0918
    # flickr:   
    # instagram: 
    linkedin: jorge-torres-374816242
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
remote_theme: huangyz0918/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
