title: Moving
author: Your Name
email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  A clean and minimalist theme for Jekyll.

show_excerpts: false # set to true to show excerpts on the homepage

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  date_format: "%b %d"
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github: jekyll
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: moving
remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
